name: nextflow_partis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.13
  - pandas=1.5.3
  - numpy=1.24.2
  - cython=0.29.34
  - mafft
  - pip
  - pip:
      - Bio==1.5.6
      - PyYAML==6.0
      - yamlloader==1.1.0
