name: partis
channels:
  - biocore
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cython=0.29.34
  - gawk=5.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - ld_impl_linux-64=2.40
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mafft=7.245
  - mpfr=4.2.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.2
  - python=3.10.13
  - python_abi=3.10
  - readline=8.2
  - setuptools=72.1.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - bio==1.5.6
      - biopython==1.84
      - biothings-client==0.3.1
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - gprofiler-official==1.0.0
      - idna==3.7
      - mygene==3.2.2
      - numpy==1.24.2
      - packaging==24.1
      - pandas==1.5.3
      - platformdirs==4.2.2
      - pooch==1.8.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0
      - requests==2.32.3
      - six==1.16.0
      - tqdm==4.66.5
      - urllib3==2.2.2
      - yamlloader==1.1.0
prefix: /hpc/home/srb108/miniconda3/envs/partis
